// Friendship #6: at rest
IF
    RealGlobalTimerExpired("I#ViconiaFriendTimer","GLOBAL")
    InParty(Myself)
    Global("I#ViconiaFriendship","GLOBAL",2)
    !AreaType(DUNGEON)
    See(Player1)
    !StateCheck(Player1,CD_STATE_NOTVALID)
    !StateCheck(Myself,CD_STATE_NOTVALID)
    CombatCounter(0)
    !See([ENEMY])
    Global("I#ViconiaFriendTalks","GLOBAL",10)
THEN
  RESPONSE #100
    IncrementGlobal("I#ViconiaFriendTalks","GLOBAL",1)
    StartDialogueNoSet(Player1)
END